services:
  shared-costs:
    image: doctordrue/shared-costs:latest
    ports:
      - "80:8080"
    volumes:
      - ./data:/workspace/data
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
    restart: always
  postgreadmin:
    image: adminer
    restart: always
    ports:
      - 8080:8080