services:
  back:
    image: doctordrue/shared-costs
    ports:
      - "80:8080"   # Application exposed
      - "5005:5005" # Java Remote debug
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
    restart: always
    volumes:
      - pg_sharedcosts:/var/lib/postgresql/data
    ports:
#      - "5432:5432" # for debug pupose

volumes:
  pg_sharedcosts:
