services:
# Application
  back:
    image: doctordrue/shared-costs
    environment:
      APP_DB_URL: jdbc:postgresql://db:5432/${APP_DB_NAME}
      APP_DB_USERNAME:  ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      APP_ADMIN_USERNAME: ${APP_ADMIN_USERNAME}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      BOT_API_URL: https://api.telegram.org/bot
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
    ports:
      - "80:8080"   # Application exposed
      - "5006:5005" # Java Remote debug
    depends_on:
      - db
    restart: always

  # Database
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    restart: always
    volumes:
      - pg_sharedcosts:/var/lib/postgresql/data
    ports:
      - "5433:5432" # For debug purpose

# Telegram bot API server for dev purpose
#  telegram-bot-api:
#    build: ./Docker/telegram-bot-api
#    ports:
#      - "8081:8081" # For debug purpose
#    environment:
#      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
#      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
#    volumes:
#      - telegram-bot-api-data:/telegram-bot-api

volumes:
  pg_sharedcosts:
#  telegram-bot-api-data:
