services:
  back:
    image: docker.io/doctordrue/shared-costs:1.0-alpha
    ports:
      - "80:8080"
      - "5005:5005"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
    restart: always
    volumes:
      - pg_sharedcosts:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  dbadmin:
#    depends_on:
#      - db
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  pg_sharedcosts:
